### PR TITLE
Fix for Issue #38

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
Reverting to non fused implementation of msub will cause performance issues as msub is used heavily in intersection kernels. aarch64 does not have an equal to x86_64 msub. 

To fix the issue we:

- reverted msub to original behaviour

- changed msub usages in the intersection kernels to use madd with negation of the pre calculated constant vale (org_rdir).

- [x] All tests pass and performance is equal/better to what was before (depends on compiler)

### CODE REVIEW

**Comment by Developer-Ecosystem-Engineering** [comment]
Neat, a failure. Investigating

**Comment by maikschulze** [comment]
I merged in https://github.com/Developer-Ecosystem-Engineering/embree-aarch64/commit/72670c7b48c0693113aa4779bb7744a37fd4ac30 and ran the verify tests again on Android arm64. The results look good:

[verify_sse2_no_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5369165/verify_sse2_no_packets.txt)
[verify_avx2_no_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5369164/verify_avx2_no_packets.txt)

[verify_sse2_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5369166/verify_sse2_with_packets.txt)
[verifx_avx2_with_packets.crashlog.txt](https://github.com/lighttransport/embree-aarch64/files/5369163/verifx_avx2_with_packets.crashlog.txt)

This pull request fixes the update failure described in https://github.com/lighttransport/embree-aarch64/issues/38 with ray packets. All tests pass for SSE2/NEON.

I also briefly inspected a test rendering collection. I do not notice any visual artifact for images created with SSE2/NEON and AVX2/NEON2X code paths.

This looks very good. Thank You!

**Comment by maikschulze** [comment]
For better reference, I've created issue https://github.com/lighttransport/embree-aarch64/issues/42 to describe the observation of the AVX2/NEON2X-related crashes with ray packets.

**Comment by syoyo** [comment]
Thanks! I'll also test the PR on Jetson AGX(aarch64 linux) soon.

**Comment by syoyo** [comment]
Hmm.. I got a following segmentation fault on Jetson AGX(aarch64 linux).

Commit: 72670c7b48c0693113aa4779bb7744a37fd4ac30

```
CC=clang CXX=clang++ $CMAKE_BIN \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DEMBREE_ARM=On \
  -DCMAKE_INSTALL_PREFIX=$HOME/local/embree3 \
  -DEMBREE_ISPC_SUPPORT=Off \
  -DEMBREE_TASKING_SYSTEM=Internal \
  -DEMBREE_TUTORIALS=Off \
  -DEMBREE_RAY_PACKETS=On \
  -DEMBREE_MAX_ISA=AVX2 \
  -DEMBREE_NEON_AVX2_EMULATION=ON \
  ..
```

Intersector8 selection is still missing for SSE2/NOEN code path?

```
                                                                          SSE2.update ...----
Thread 20 "verify" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fae79e1b0 (LWP 1642)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000007fb74649f0 in embree::Accel::Intersectors::intersect8 (this=0x7f900c3678, valid=0x7fae784a40, 
    ray=..., context=0x7fae784b10) at /home/syoyo/work/embree-aarch64-neon2x/kernels/common/accel.h:319
#2  embree::AccelN::intersect8 (valid=0x7fae784a40, This_in=<optimized out>, ray=..., context=0x7fae784b10)
    at /home/syoyo/work/embree-aarch64-neon2x/kernels/common/acceln.cpp:65
#3  0x0000007fb7c5e43c in embree::Accel::Intersectors::intersect8 (this=0x7f900c2538, valid=0x7fae784a40, 
    ray=..., context=0x7fae784b10)
    at /home/syoyo/work/embree-aarch64-neon2x/kernels/bvh/../common/accel.h:319
#4  embree::Accel::Intersectors::intersect (this=0x7f900c2538, valid=..., ray=..., context=0x7fae784b10)
    at /home/syoyo/work/embree-aarch64-neon2x/kernels/bvh/../common/accel.h:344
#5  embree::avx2::RayStreamFilter::filterSOA<8, true> (scene=0x7f900c24e0, rayData=<optimized out>, 
    N=<optimized out>, numPackets=1, stride=320, context=0x7fae784b10)
    at /home/syoyo/work/embree-aarch64-neon2x/kernels/bvh/bvh_intersector_stream_filters.cpp:442
#6  0x0000007fb7488c0c in rtcIntersectNM (hscene=0x7f900c24e0, user_context=<optimized out>, rayhit=0x0, 
    N=<optimized out>, M=<optimized out>, byteStride=547879127568)
    at /home/syoyo/work/embree-aarch64-neon2x/kernels/common/rtcore.cpp:687
#7  0x00000055555956e8 in embree::IntersectWithNMMode<4> (ivariant=<optimized out>, scene=<optimized out>, 
    context=<optimized out>, rays=0x7fae79ae20, Nrays=1)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/rtcore_helpers.h:695
#8  0x000000555556e754 in embree::IntersectWithModeInternal (mode=<optimized out>, ivariant=<optimized out>, 
    scene=0x7f900c24e0, rays=0x7fae79ae20, N=0, context=0x7fae79ad08)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/rtcore_helpers.h:863
#9  0x00000055555aa184 in embree::UpdateTest::run (this=0x55556e3510, state=<optimized out>, 
    silent=<optimized out>) at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/verify.cpp:1774
#10 0x00000055555702f8 in embree::VerifyApplication::Test::execute (this=0x55556e3510, state=0x7fffffebb8, 
    silent=true) at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/verify.cpp:420
#11 0x00000055555911ac in embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0::operator()(unsigned long) const (this=<optimized out>, i=<optimized out>)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/verify.cpp:673
#12 embree::parallel_for<unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0>(unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0 const&)::{lambda(embree::range<unsigned long> const&)#1}::operator()(embree::range<unsigned long> const&) const (this=<optimized out>, r=...)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/../../common/algorithms/parallel_for.h:27
#13 embree::TaskScheduler::spawn<unsigned long, embree::parallel_for<unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0>(unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0 const&)::{lambda(embree::range<unsigned long> const&)#1}>(unsigned long, unsigned long, unsigned long, embree::parallel_for<unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0>(unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0 const&)::{lambda(embree::range<unsigned long> const&)#1} const&)::{lambda()#1}::operator()() const (this=<optimized out>)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/../../kernels/common/../../common/tasking/taskschedulerinternal.h:315
#14 embree::TaskScheduler::ClosureTaskFunction<embree::TaskScheduler::spawn<unsigned long, embree::parallel_for<unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0>(unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0 const&)::{lambda(embree::range<unsigned long> const&)#1}>(unsigned long, unsigned long, unsigned long, embree::parallel_for<unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0>(unsigned long, embree::VerifyApplication::TestGroup::execute(embree::VerifyApplication*, bool)::$_0 const&)::{lambda(embree::range<unsigned long> const&)#1} const&)::{lambda()#1}>::execute() (this=<optimized out>)
    at /home/syoyo/work/embree-aarch64-neon2x/tutorials/verify/../../kernels/common/../../common/tasking/taskschedulerinternal.h:47
#15 0x0000007fb7ebad00 in embree::TaskScheduler::Task::run_internal (this=<optimized out>, thread=...)
    at /home/syoyo/work/embree-aarch64-neon2x/common/tasking/taskschedulerinternal.cpp:53
#16 0x0000007fb7ebaf98 in embree::TaskScheduler::TaskQueue::execute_local_internal (this=0x7f908f9a00, 
    thread=..., parent=0x7fae7847c0)
    at /home/syoyo/work/embree-aarch64-neon2x/common/tasking/taskschedulerinternal.cpp:85
#17 0x0000007fb7ebc32c in embree::TaskScheduler::wait ()
    at /home/syoyo/work/embree-aarch64-neon2x/common/tasking/taskschedulerinternal.cpp:329
#18 0x0000007fb7ebad00 in embree::TaskScheduler::Task::run_internal (this=<optimized out>, thread=...)
    at /home/syoyo/work/embree-aarch64-neon2x/common/tasking/taskschedulerinternal.cpp:53
#19 0x0000007fb7ebaf98 in embree::TaskScheduler::TaskQueue::execute_local_internal (this=0x7f908f9a00, 
    thread=..., parent=0x7fae7847c0)
```

**Comment by maikschulze** [comment]
The segmentation fault is caused by https://github.com/lighttransport/embree-aarch64/issues/42 .

I would recommend that we consider this a separate issue. This pull request should be verifiable with

CC=clang CXX=clang++ $CMAKE_BIN \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DEMBREE_ARM=On \
  -DCMAKE_INSTALL_PREFIX=$HOME/local/embree3 \
  -DEMBREE_ISPC_SUPPORT=Off \
  -DEMBREE_TASKING_SYSTEM=Internal \
  -DEMBREE_TUTORIALS=Off \
  -DEMBREE_RAY_PACKETS=On \
  -DEMBREE_MAX_ISA=SSE2 \
  -DEMBREE_NEON_AVX2_EMULATION=OFF \
  ..

just for SSE2/NEON. Then, in a separate, future, pull request we can address the AVX2/NEON2X crash and possibly masked verify failures for ray packets.

**Comment by syoyo** [comment]
@maikschulze I see. I just thought the PR already contains a fix for #42 . I'll test this PR with ray_packets=off

**Comment by syoyo** [comment]
Merged with a description of known issue: https://github.com/lighttransport/embree-aarch64#embree-on-aarch64arm64-status

**Pull request merged**
