### PR TITLE
Improved the performance for iOS.

### PR DESCRIPTION
**Pull request by pchang0414**
Optimization on vector code for multi-core on iOS.

### CODE REVIEW

**Comment by syoyo** [comment]
Awesome!  Will check it soon!

Do you have any number for the improved performance?

**Comment by pchang0414** [comment]
It varies depending on the test cases.
We used about 100 different test cases with various models.

Paul.

**Comment by syoyo** [comment]
I see > test cases

I have added some modification and pushed to `pchang0414-iOS-Opt ` branch.

It sill require some amount of work for AARCH64 target.

NEON code in PR does not have  conversion-free casting(reinterpreting SIMD types using `vreinterpret***` intrinsics), so it fails to compile with aarch64-gcc(or maybe clang with strict compiler options. I do not want to use `-flax-vector-conversions` to suppress conversion-free casting)

```
4 /home/syoyo/work/embree-aarch64/common/math/SSE2NEON.h:871 col 26: note: use -flax-vector-conversions to permit conversions between vectors with differing element types
or numbers of subparts
 7 /home/syoyo/work/embree-aarch64/common/math/SSE2NEON.h:871 col 22: error: cannot convert ‘__m128i’ {aka ‘__vector(4) int’} to ‘uint32x4_t’ {aka ‘__vector(4) unsigned int
’}
```

**Comment by pchang0414** [comment]
We will try to reproduce this problem and get back to you.
Thank you for looking into this problem.

**Comment by pchang0414** [comment]
I tried to compile iOS version with -fno-lax-vector-conversions but the compilation is already failing by inclusion of “arm_neon.h”.
Since we can’t change system header file, I think it’s better to reproduce this problem on linux.

I’ve set up the linux machine with gcc compiler but it seems that "scripts/bootstrap-aarch64-gcc-cross-linux.sh” failing to compile for arm64 architecture and building for x86_64.

What am I missing?

How do we compile for aarch64 on linux?

Thank you.
Paul.

**Comment by syoyo** [comment]
> How do we compile for aarch64 on linux?

I'm using gcc8(`g++-8-aarch64-linux-gnu` apt package on Ubuntu 18.04)

```
CMAKE_BIN=cmake

rm -rf build-aarch64-cross

$CMAKE_BIN \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DEMBREE_ARM=On \
  -DEMBREE_ADDRESS_SANITIZER=On \
  -DCMAKE_INSTALL_PREFIX=$HOME/local/embree3 \
  -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc-8 \
  -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++-8 \
  -DEMBREE_ISPC_SUPPORT=Off \
  -DEMBREE_TASKING_SYSTEM=Internal \
  -DEMBREE_TUTORIALS=Off \
  -DEMBREE_MAX_ISA=SSE2 \
  -DEMBREE_RAY_PACKETS=Off \
  -Bbuild-aarch64-cross -H.
```

Then you'll get an error something like this:

```
...
cd /home/syoyo/work/embree-aarch64/build-aarch64-cross/common/sys && /usr/bin/aarch64-linux-gnu-g++-8  -DEMBREE_TARGET_SSE2 -DTASKING_INTERNAL  -Wall -Wformat -Wformat-security -fPIE -fPIC -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -fno-strict-aliasing -fno-tree-vectorize  -DDEBUG -DTBB_USE_DEBUG -g -O3 -D_FORTIFY_SOURCE=2     -o CMakeFiles/sys.dir/sysinfo.cpp.o -c /home/syoyo/work/embree-aarch64/common/sys/sysinfo.cpp
...
In file included from /home/syoyo/work/embree-aarch64/common/sys/intrinsics.h:26,
                 from /home/syoyo/work/embree-aarch64/common/sys/sysinfo.cpp:18:
/home/syoyo/work/embree-aarch64/common/sys/../math/SSE2NEON.h: In function ‘__m128i _mm_srli_epi32(__m128i, int)’:
/home/syoyo/work/embree-aarch64/common/sys/../math/SSE2NEON.h:871:26: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
     return vshlq_u32(a, s);
                          ^
/home/syoyo/work/embree-aarch64/common/sys/../math/SSE2NEON.h:871:22: error: cannot convert ‘__m128i’ {aka ‘__vector(4) int’} to ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’}
     return vshlq_u32(a, s);
                      ^
...
```

**Comment by syoyo** [comment]
I have setup Github Actions for aarch64 cross-compiling.

https://github.com/lighttransport/embree-aarch64/blob/master/.github/workflows/ccpp.yml
https://github.com/lighttransport/embree-aarch64/actions

Build will also be triggered when you push further commit to PR.

**Comment by pchang0414** [comment]
I was able to reproduce this problem now with "g++-8-aarch64-linux-gnu apt package on Ubuntu 18.04”.
But I wonder what the reason is that we can’t use -flax-vector-conversions.

This project is emulating Intel vector code into Neon.
Intel vector code doesn’t distinguish between vector types.
Only types that Intel vector code cares are either “float” vector or “integer” vector.

Is there a reason that we have to be more strict on Neon code for vector type conversion?

Paul.

**Comment by syoyo** [comment]
vector-type has different semantics/syntax over compilers and architectures.

For example, NEON and AltiVec(and as far as I remembered PS3's Cell SPU) need explicit casting for conversion-free casting(preserving bit patterns). 
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0472j/chr1359125040547.html
https://www.nxp.com/docs/en/reference-manual/ALTIVECPIM.pdf

> Is there a reason that we have to be more strict on Neon code for vector type conversion?

To avoid normal type casting with implicit casting. for example some archtecture/compiler(e.g. NEON/AltiVec) may upcast, downcast, or actually convert values(changing bit patterns).

**Comment by syoyo** [comment]
http://www.informit.com/articles/article.aspx?p=1732873&seqNum=6

More detailed article about vector-type casting.

**Comment by pchang0414** [comment]
Sure, we get your point.

We spent about a few hours yesterday to go over these errors.
It turns out that the required changes are significant.
The problem is that we can’t test these new changes on gcc / Linux environment in the same way we did on iOS because we can’t port the test apps that we used from iOS to Linux.
We don’t feel comfortable to run these significant amount of change that we didn’t test by ourselves on gcc / Linux.

So, we want to limit our change to clang / iOS because we feel confident after the good set of tests that we did.

Is it ok with you?

**Comment by syoyo** [comment]
> So, we want to limit our change to clang / iOS because we feel confident after the good set of tests that we did.

So a possible solution you can do is

```
#if defined(__aarch64__)
#if defined(__clang__) // or IOS
  your PR code here
#else // e.g. gcc on aarch64 linux
  previous code here 
#endif
#endif
```

When I had a time at some point, I will work on inserting `vreinterpret*` intrinsics and unify clang/gcc code paths. 

BTW, clang may change lax-vector-conversion behaviour in the future:
 
PR17164: Change clang's default behaviour from -flax-vector-conversions=all to -flax-vector-conversions=integer.
https://reviews.llvm.org/D67678

This may also affect the future iOS clang behaviour on vector intrinsics.

**Comment by pchang0414** [comment]
We used “defined(BUILD_IOS)” to enable our optimization work only for iOS.

We just checked in the changes.

Please let us know if there is any problem.

Thank you.

**Comment by syoyo** [comment]
Awesome! Thank you!

I did some small modification and added iOS build to GitHub Actions. iOS build is working well.

https://github.com/lighttransport/embree-aarch64/commit/e83766965efe25c113336345879b4081a21a2d3d/checks?check_suite_id=325260095

**Comment by pchang0414** [comment]
Great news, thank you very much.
Paul.

**Comment by syoyo** [comment]
@pchang0414 Embree v3.7.0 is out and I've synced it to embree-aarch64. 

https://github.com/lighttransport/embree-aarch64/tree/origin/v3.7.0

Could you please try v3.7.0 on iOS(with your test scenes) if you have time?

**Comment by pchang0414** [comment]
Sure.

I will discuss about when we can do this and get back to you.

Thank you.
Paul.

**Pull request merged**
