### PR TITLE
Fix sqrt(0) -> 0 instead of +inf for arm64.

### PR DESCRIPTION
**Pull request by maikschulze**
This code change fixes the issue raised here: https://github.com/lighttransport/embree-aarch64/issues/30

### CODE REVIEW

**Comment by maikschulze** [comment]
I observe the following behavior on Android arm64 and iOS arm64.
Left: Android arm64 without the fix, Right: Android arm64 with the fix.

image

image

**Comment by maikschulze** [comment]
As a side note: I have manually evaluated the difference images of x64 vs. Android arm64 of my test suite and cannot find any artifact that's specific to arm64. This is a good version!

**Comment by syoyo** [comment]
@maikschulze Awesome! Let me give some time to check if changes also works well on our platform(Jetson AGX aarch64 Ubuntu 18.04)

**Comment by syoyo** [comment]
@maikschulze Confirmed aarch64 linux version works well(no holes for curves geometry) so merged! Good job!

**Pull request merged**
