### PR TITLE
Merge v3.12.0 from upstream main Embree repo

### PR DESCRIPTION
**Pull request by betajippity**
This merge request merges Embree v3.12.0 from the upstream Intel Embree repo into embree-aarch64. Embree v3.12.0 changes have been tested and confirmed to work on Apple Silicon and aarch64 Linux (Fedora 32).

### CODE REVIEW

**Comment by syoyo** [comment]
Super awesome! :tada:

Let us give time to check if the PR runs well on other aarch64 variant(especially Jetson AGX). And also we'll need to check if Neon2x PR https://github.com/lighttransport/embree-aarch64/pull/34 can be applied after(or before) this v3.12.0 merge PR.

**Comment by betajippity** [comment]
Yup, sounds good! Let me know if there's anything that needs to be fixed.

**Comment by syoyo** [comment]
I have encountered the build failure of `bvh_access` tutorial.

```
/home/syoyo/work/embree-aarch64/tutorials/bvh_access/bvh_access.cpp:238: undefined reference to `embree::waitForKeyPressedUnderWindows()'
```

After some investigation, I found it looks your merge does not reflect changes of original Intel embree of this commit: https://github.com/embree/embree/commit/b62a7b6e53c26217a15b59522ddd8abac4ddca3d

For example, `bvh_access/CMakeLists.txt` is still using older one 

https://github.com/betajippity/embree-aarch64/blob/master/tutorials/bvh_access/CMakeLists.txt
(linking with `tutorial` is missing. even though `git log` shows the commit b62a7b6e53c26217a15b59522ddd8abac4ddca3d is included in your repo)

Intel embree.
https://github.com/embree/embree/blob/master/tutorials/bvh_access/CMakeLists.txt

@betajippity Do you happen to know the reason of this inconsistency?

**Comment by syoyo** [comment]
I have manually merged Intel v3.12.0 to embree-aarch64 `master`, then `verify` started to report lots of failures(this also happens to your PR)

We need to investigate the reason of `verify` failures before the merge of PR.

OS: Jetson AGX(aarch64 linux)
Configuration: `scripts/bootstrap-aarch64-linux.sh`

```
Embree Ray Tracing Kernels 3.12.0 (b2e495336782d9ff20e59bf1f45cc7633bda7c5f)
  Compiler  : GCC 7.5.0
  Build     : Release 
  Platform  : Linux (32bit)
  CPU       : Unknown CPU ( MRA MRA MRA)
   Threads  : 8
   ISA      : SSE SSE2 NEON 
   Targets  : 
   MXCSR    : FTZ=0, DAZ=0
  Config
    Threads : default
    ISA     : SSE SSE2 NEON 
    Targets :  (supported)
              SSE2  (compile time enabled)
    Features: intersection_filter 
    Tasking : internal_tasking_system 

================================================================================
  WARNING: "Flush to Zero" or "Denormals are Zero" mode not enabled 
           in the MXCSR control and status register. This can have a severe 
           performance impact. Please enable these modes for each application 
           thread the following way:

           #include "xmmintrin.h"
           #include "pmmintrin.h"

           _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
           _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
================================================================================


 [PASSED]
                                                       fast_allocator_regression_test ... [PASSED]
                                                         motion_derivative_regression ... [PASSED]
                                                            collision_regression_test ... [PASSED]
                                                                cache_regression_test ... [PASSED]
                                                         parallel_for_regression_test ... [PASSED]
                                                      parallel_reduce_regression_test ... [PASSED]
                                                       parallel_prefix_sum_regression ... [PASSED]
                                                     parallel_for_for_regression_test ... [PASSED]
                                          parallel_for_for_prefix_sum_regression_test ... [PASSED]
                                                   parallel_partition_regression_test ... [PASSED]
                                                           RadixSortRegressionTestU32 ... [PASSED]
                                                           RadixSortRegressionTestU64 ... [PASSED]
                                                         parallel_set_regression_test ... [PASSED]
                                                         parallel_map_regression_test ... [PASSED]
                                                           parallel_filter_regression ... [PASSED]
                                                          barrier_sys_regression_test ... [PASSED]
                                                                NEON.multiple_devices ... [FAILED]
                                                                      NEON.types_test ... [PASSED]
                                                                      NEON.get_bounds ...---------------- [FAILED]
                                                               NEON.get_linear_bounds ...---------------- [FAILED]
                                                                   NEON.get_user_data ... [FAILED]
                                                                   NEON.buffer_stride ...-------- [FAILED]
                                                                     NEON.empty_scene ...---------- [FAILED]
                                                                  NEON.empty_geometry ...---------- [FAILED]
                                                                           NEON.build ...---------- [FAILED]
                                                          NEON.overlapping_primitives ...---------- [FAILED]
                                                             NEON.new_delete_geometry ...----- [FAILED]
                                                                NEON.user_geometry_id ...----- [FAILED]
                                                         NEON.enable_disable_geometry ...----- [FAILED]
                                                                          NEON.update ...---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                              NEON.build_garbage_geom ... [FAILED]
                                                           NEON.interpolate.triangles ...------ [FAILED]
                                                                NEON.interpolate.grid ...------ [FAILED]
                                                              NEON.interpolate.subdiv ...------ [FAILED]
                                                                NEON.interpolate.hair ...------ [FAILED]
                                                                    NEON.triangle_hit ...---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                                        NEON.quad_hit ...---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                             NEON.intersection_filter ...-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                                      NEON.instancing ...-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                                   NEON.inactive_rays ...---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [FAILED]
                                                            NEON.watertight_triangles ...------------------------------------------------------------------------------------------------ [FAILED]
                                                         NEON.watertight_triangles_mb ...------------------------------------------------------------------------------------------------ [FAILED]
                                                                NEON.watertight_quads ...------------------------------------------------------------------------------------------------ [FAILED]
                                                             NEON.watertight_quads_mb ...------------------------------------------------------------------------------------------------ [FAILED]
                                                                NEON.watertight_grids ...------------------------------------------------------------------------------------------------ [FAILED]
                                                             NEON.watertight_grids_mb ...------------------------------------------------------------------------------------------------ [FAILED]
                                                               NEON.watertight_subdiv ...!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [PASSED]
                                                              NEON.ray_alignment_test ...------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ [FAILED]
                                                                     NEON.point_query ...----------------------- [FAILED]
                                                               NEON.regression_static ... [FAILED]
                                                              NEON.regression_dynamic ... [FAILED]
                                                    NEON.regression_static_build_join ... [FAILED]
                                                   NEON.regression_dynamic_build_join ... [FAILED]
                                                NEON.regression_static_memory_monitor ... [FAILED]
                                               NEON.regression_dynamic_memory_monitor ... [FAILED]
                                                            NEON.geometry_state_tests ... [FAILED]
                                                   NEON.scene_modified_geometry_tests ... [FAILED]
                                                   NEON.sphere_filter_multi_hit_tests ... [PASSED]

                                                                         Tests passed: 19
                                                                         Tests failed: 5051
                                                             Tests failed and ignored: 96
```

**Comment by betajippity** [comment]
In the case of `bvh_access/CMakeLists.txt`, if I remember correctly, there were merge conflicts between embree-aarch64 and the mainline Embree repo. I went with what was in embree-aarch64, but maybe it should have been what was in the mainline repo?

I haven't looked into the `verify` failures yet; if I have time, I'll look into it soon.

**Comment by syoyo** [comment]
@betajippity For `verify` failure, the reason was `checkISASupport()` returns false when Embree Device is initialized with `isa=neon`. I have fixed it in this commit: https://github.com/lighttransport/embree-aarch64/commit/b9a8fa12cd166dec1ad9ed08ded2f6b0805e28ab and `verify` goes well(except for `NEON.update` failure https://github.com/lighttransport/embree-aarch64/issues/38)

Could you please try our version of v3.12.0 merge? It should be mostly identical to your PR and it fixes `bvh_access` build(need to add linking with `tutorial` library when merging) https://github.com/lighttransport/embree-aarch64

**Comment by syoyo** [comment]
v3.12.0 changes are merged into `main` with some other fixes and here is the branch for aarch64 v3.12.0 release: https://github.com/lighttransport/embree-aarch64/tree/aarch64-v3.12.0

**Pull request closed without merging**
