### PR TITLE
Merge v3.12.2 from upstream main Embree repo

### PR DESCRIPTION
**Pull request by betajippity**
This is a draft attempt at merging v3.12.2 from the upstream mainline Embree repo. The main changes revolve around the removal of KNL-specific codepaths, which resulted in all AVX512 code being merged into a single codepath. I made an attempt to resolve all of the merge conflicts, and testing using embree-verify (they renamed verify to embree-verify) seems to look good on my Apple Silicon machine and on aarch64 Fedora 33, but I haven't been able to test everything that embree-aarch64 supports.

### CODE REVIEW

**Comment by syoyo** [comment]
Thanks! Let us give some time to review PR. 

FYI there is an activity to support arm64 at official Intel embree repo: https://github.com/embree/embree/pull/316

embree-aarch64 development would be discontinued once official Intel embree fully supports arm64 target.

**Comment by syoyo** [comment]
The PR revert to use embree's local glfw3 and TBB cmake. Apparently it now works well on M1 macOS environment, but it may be better stick to use cmake's system package as @Twinklebear committed here  https://github.com/lighttransport/embree-aarch64/commit/0ac250269c596c9d699e75bc81a8a92514dec99b  @Twinklebear how do you think?

**Comment by Twinklebear** [comment]
The issue I ran into is their FindTBB wasn't working with the more recent TBB I downloaded (`TBB_INCLUDE_DIRS` and `TBB_LIBRARIES` were empty). We could change to use theirs and just encourage all M1 users to build the embedded TBB instead. The FindGLFW3 I think is also ok to add back in, I think that should work with a locally built glfw3 as well, I don't remember if I ran into issues here.

But given Sven's comment that it's on the roadmap https://github.com/embree/embree/pull/316#issuecomment-780385226 we may not need this fork for too much longer, which would be cool.

**Comment by syoyo** [comment]
@Twinklebear Thanks! So it would be OK to revert to use embree's FindTBB and FindGLFW3 package and keep the cmake script same as much as possible with Intel embree's repo.

**Comment by Twinklebear** [comment]
M1 support is in the 3.13 release 🎉 https://github.com/embree/embree/releases/tag/v3.13.0

**Comment by syoyo** [comment]
@Twinklebear Good to know! 

Added a description of project status: https://github.com/lighttransport/embree-aarch64/commit/0e55e5497ff1ca1ab75c503c6cac0022a4cab0b9

We are busy on our own raytracing engine development and have very limited bandwidth to support embree-aarch64, thus this PR  won't be merged unless @betajippity solves merge conflicts and fixes CI builds.

**Comment by betajippity** [comment]
With the recent release of Embree v3.13.0, I think there's no longer any need to merge this request. I've built and test Embree v3.13.0 on both an M1 Mac and on an aarch64 Raspberry Pi 4, and on both it works exactly as advertised. Performance between embree-aarch64 and official Embree v3.13.0 on arm64/aarch64 is pretty much the same too. :)

**Comment by syoyo** [comment]
> I've built and test Embree v3.13.0 on both an M1 Mac and on an aarch64 Raspberry Pi 4, and on both it works exactly as advertised. Performance between embree-aarch64 and official Embree v3.13.0 on arm64/aarch64 is pretty much the same too. :)

👌

**Pull request closed without merging**
