### PR TITLE
Neon2x for Apple silicon

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
Adding support for AVX2 using 2x neon

### CODE REVIEW

**Comment by syoyo** [comment]
Super Awesome!

Let us give some time to check if Neon2x mode works well on other ARM architecture(e.g. Jetson AGX)

Do you have numbers on the performance of AVX(Neon2x) version compared to SSE2(Neon) version?(especially in terms of energy consumption. e.g. N rays per seconds per watt)

**Comment by syoyo** [comment]
@Developer-Ecosystem-Engineering How to enable AVX2 simulation(neon2x) build on non-Apple Silicon platform?(neon2x should be available all aarch64 CPUs)

**Comment by maikschulze** [comment]
Hi,

while I'm not the author and cannot give you any exact numbers, I can at least assert that qualitatively the code changes appear to be fine for me. I cannot observe any quality artifacts or slowdowns when running a personal test series, similar to a previous report: https://github.com/lighttransport/embree-aarch64/issues/17#issuecomment-592983783 . The test hardware was an iPad Air with an A12 CPU and an iPad Pro with an A12X CPU.

I have not attempted to run this on Android devices.

**Comment by Developer-Ecosystem-Engineering** [comment]
> Super Awesome!
> 
> Let us give some time to check if Neon2x mode works well on other ARM architecture(e.g. Jetson AGX)
> 
> Do you have numbers on the performance of AVX(Neon2x) version compared to SSE2(Neon) version?(especially in terms of energy consumption. e.g. N rays per seconds per watt)

AS_MAC is the cmake bool which enables neon 2x mode in Embree. We did not test, but expecting all current arm CPUs to perform slower in this mode. Functionally this mode should work on all aarch64 devices

Existing Apple silicon chips will perform faster, e.g. iPad A12X.

**Comment by syoyo** [comment]
@Developer-Ecosystem-Engineering Thanks! > AS_MAC

But it gets compilation error on non-apple clang and gcc

```
/home/syoyo/work/embree-aarch64-neon2x/common/sys/../math/SSE2NEON.h:920:26: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
     return vshlq_u32(a, s);
```

As discussed in https://github.com/lighttransport/embree-aarch64/pull/14 , explicit type conversion is required to avoid potential bugs.

**Comment by Developer-Ecosystem-Engineering** [comment]
> @Developer-Ecosystem-Engineering Thanks! > AS_MAC
> 
> But it gets compilation error on non-apple clang and gcc for example:
> 
> ```
> /home/syoyo/work/embree-aarch64-neon2x/common/sys/../math/SSE2NEON.h:920:26: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
>      return vshlq_u32(a, s);
>                           ^
> ```
> 
> As discussed in #14 , explicit type conversion is required to avoid potential bugs.

Ah, GCC. Okay, will address in a subsequent modification to this PR.
-flax-vector should resolve it

**Comment by syoyo** [comment]
> -flax-vector should resolve it

No, `-flax-vector-conversion` should not be used even on clang. Its a source of potential bugs 
 
https://bugs.llvm.org/show_bug.cgi?id=17164

But for historical reason & backward compatibility, `-flax-vector-conversion` is enabled by default in (Apple) clang. Its not a recommended situation. 

https://reviews.llvm.org/D67160

**Comment by Developer-Ecosystem-Engineering** [comment]
Okay, reverted to master and re-applied with updated changes

**Comment by syoyo** [comment]
@Developer-Ecosystem-Engineering Awesome!

I have confirmed now `verify` passes well.

For gcc-8/9/10, I have encountered internal compilation error and filed it to https://github.com/lighttransport/embree-aarch64/issues/40 (and also proposing possible fix)

Another issue of gcc is compilation become too slow on native aarch64 linux(Jetson AGX) due to this issue: https://github.com/lighttransport/embree-aarch64/issues/21
(Didn't finish to compile curve_intersector_virtual.cpp.avx2.cpp and curve_intersector_virtual2.cpp.avx2.cpp after 20~30 mins even disabling optimization(`-O0`). 

I will merge PR soon after confirming some of tutorial code runs well on our side(Jetson AGX)

**Comment by maikschulze** [comment]
Hi,

I have run the 'verify' tests on my Android smart phone OnePlus3T (Snapdragon 821 CPU) and enclose the log files:

I have run it on the 'before' state, i.e. 
https://github.com/lighttransport/embree-aarch64/commit/3f6b20800e28f2bc92e018b5d71190489becd22f
and the 'after' state, i.e. 
https://github.com/Developer-Ecosystem-Engineering/embree-aarch64/commit/ea648419af81c014ff0dd9fb045d13b5f470f424
with varying CMake options:

1. Before, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=OFF 
[verify_before_sse2_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5360670/verify_before_sse2_without_packets.txt)

2. Before, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=ON
[verify_before_sse2_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5360669/verify_before_sse2_with_packets.txt)

3. After, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=OFF 
[verify_after_sse2_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5360668/verify_after_sse2_without_packets.txt)

4. After, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=ON
[verify_after_sse2_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5360667/verify_after_sse2_with_packets.txt)

5. After, -DEMBREE_MAX_ISA=AVX2, -DEMBREE_NEON_AVX2_EMULATION=ON , -DEMBREE_RAY_PACKETS=OFF
[verify_after_avx2_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5360666/verify_after_avx2_without_packets.txt)

6. After, -DEMBREE_MAX_ISA=AVX2, -DEMBREE_NEON_AVX2_EMULATION=ON , -DEMBREE_RAY_PACKETS=ON
[verify_after_avx2_with_packets.crashlog.txt](https://github.com/lighttransport/embree-aarch64/files/5360671/verify_after_avx2_with_packets.crashlog.txt)

I conclude the following:

a) This PR fixes https://github.com/lighttransport/embree-aarch64/issues/28 . This is awesome!

b) This PR fixes issues with 'update' tests for SSE2 and AVX2 mode when ray packets are OFF. When ray packets are ON, the update tests fail or crash. We should investigate this issue as https://github.com/lighttransport/embree-aarch64/issues/38 .

c) At least in the context of the 'verify' test suite the ISA detection for 2xNEON seems off. Log 5.) presents it as mixture of SSE and AVX2. We may want to explore options to improve this.

**Comment by syoyo** [comment]
@maikschulze Nice!

Could you please try `lighttransport/Developer-Ecosystem-Engineering-master` branch again? https://github.com/lighttransport/embree-aarch64/tree/Developer-Ecosystem-Engineering-master

It merges v3.12.0 PR https://github.com/lighttransport/embree-aarch64/pull/35 and contains fix for https://github.com/lighttransport/embree-aarch64/issues/40 and https://github.com/lighttransport/embree-aarch64/issues/21

`verify` should pass when EMBREE_RAY_PACKETS=OFF

Once this branch is merged, the `main` branch will contain v3.12.0 and NEONx2 feature.

**Comment by maikschulze** [comment]
Hi @syoyo ,

thanks a lot for your merge with 3.12. I have run the four different configurations on Android for branch
https://github.com/lighttransport/embree-aarch64/commit/ba6d997e66d8d15dc176727857900637be0bc832 :

1. Merge, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=OFF
[verify_merge_sse2_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5361206/verify_merge_sse2_without_packets.txt)

2. Merge, -DEMBREE_MAX_ISA=SSE2 , -DEMBREE_NEON_AVX2_EMULATION=OFF , -DEMBREE_RAY_PACKETS=ON
[verify_merge_sse2_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5361205/verify_merge_sse2_with_packets.txt)

3. Merge, -DEMBREE_MAX_ISA=AVX2, -DEMBREE_NEON_AVX2_EMULATION=ON , -DEMBREE_RAY_PACKETS=OFF
[verify_merge_avx2_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5361204/verify_merge_avx2_without_packets.txt)

4. Merge, -DEMBREE_MAX_ISA=AVX2, -DEMBREE_NEON_AVX2_EMULATION=ON , -DEMBREE_RAY_PACKETS=ON
[verify_merge_avx2_with_packets.crashlog.txt](https://github.com/lighttransport/embree-aarch64/files/5361203/verify_merge_avx2_with_packets.crashlog.txt)

I obtain the same 'verify' results as before and therefore conclude that the merge went well and the contributions of this PR still have the same positive effect.

**Comment by syoyo** [comment]
@maikschulze Thanks! this PR has been merged into `main`(master) with v3.12.0 and other fixes.

**Pull request merged**
