### PR TITLE
Fixes to build tutorials and ISPC support on Apple Silicon

### PR DESCRIPTION
**Pull request by Twinklebear**
This PR updates the tutorials to be buildable and runnable on M1-based macs by:

- Updating how they search for GLFW to use a CMake 3+ approach to find GLFW and link it
- Not aborting on all GLFW errors, as one warning seems to fire when running on M1 (at least today on the latest GLFW and 11.0.1)
- Disabling `CATCH_TRAP` on aarch64 targets as it's only applicable to x86_64. There might be a way to do this on Arm but it seems like it varies, vs. x86 where it's just `int $3`.

This PR also updates the code to find and link TBB using an external TBB and the CMake 3+ find package approach. This lets you use TBB on M1 macs w/ embree-aarch64, though you have to build TBB from source. This may cause some issues with the embedded TBB approach, but a better approach for that might be CMake external projects instead of `add_subdirectory`

I removed both FindGLFW3.cmake and FindTBB.cmake in this PR since they can now be found using the CMake 3 style of setting `glfw_DIR` and `TBB_DIR` to point to locations with a `<package>Config.cmake` file.

This PR also allows ISPC support for embree-aarch64 and modifies the ISPC cmake script to target neon-i32x4, which in some small testing I found to give slightly better performance. Currently this does need my fork of ISPC that enables a macOS + arm/neon target: https://github.com/Twinklebear/ispc

Let me know how this looks, and if anything should be changed. Thanks for embree-aarch64!

### CODE REVIEW

**Comment by syoyo** [comment]
@Twinklebear Super awesome! :tada:

Could you provide the detail of TBB build on M1 macOS(TBB version(do you use oneTBB?), cmake bootstrap command, etc) so that we can test building your PR with external TBB build?

**Comment by Twinklebear** [comment]
Yes this is using oneTBB, I just took the latest release off Github.

I just added instructions on building with TBB and ISPC support that include the CMake command for TBB (needs some options set), guide on getting and building the right ISPC (just using their build script), and the CMake command to build Embree with TBB, ISPC and the tutorials enabled. Let me know if you run into issues trying to build it

**Comment by syoyo** [comment]
@Twinklebear Thanks! At least I can compile and run M1 build with TBB(recent oneTBB) using your procedure. 

ISPC is not yet tested(since it takes few hours to compile :cry:)

But when I run tutorial(e.g. `curve_geometry`), I got lots of warnings on thread affinity.
(I'm using macport glfw 3.3.2)

https://github.com/lighttransport/embree-aarch64/blob/b81394d34c0ad79fd51540b574daf6ec915c0262/common/sys/thread.cpp#L295

```
Warning: setting thread affinity failedsetting thread affinity failed
Warning: 

setting thread affinity failed

Warning: setting thread affinity failed
Warning: setting thread affinity failed
Warning: setting thread affinity failedWarning: Warning: setting thread affinity failed

Warning: setting thread affinity failed
setting thread affinity failed
Warning: setting thread affinity failed
```


TBB used is:

```
commit 8dcbd5b11bfd84d09d1af1e11d4dfd68ab3b680b
Author: tbbdev <inteltbbdevelopers@intel.com>
Date:   Wed Nov 18 12:07:23 2020 +0300

    Commit oneTBB source code 8fda6294
```

We may be OK to disable thread affinity warnings on M1 macOS for a while.

**Comment by Twinklebear** [comment]
Yeah, I've been passing `--set_affinity 0` when running the tutorials, but what would work best is to actually set it off by default. I'll add this change

**Comment by Twinklebear** [comment]
This was actually an issue in the tutorials which were always requesting affinity to be set on by default, I've removed that in 6ef362f and no longer get the warnings.

**Comment by Twinklebear** [comment]
Actually one last thing I want to try before merging this is setting the flush zero modes for the tutorials, that might help performance quite a bit

**Comment by Twinklebear** [comment]
It actually looks like this doesn't have much effect, after testing with setting flush to zero via `fesetenv` from `<fenv.h>`

```c
    fesetenv(&_FE_DFL_DISABLE_DENORMS_ENV);
```

then

```c++
    float x = FLT_MIN;
    std::cout << x/2.f << '\n';
```

Prints 0, but performance on the examples is the same.

**Comment by syoyo** [comment]
@Twinklebear Thanks! > affinity

For DAZ and FTZ, I also tested it on Jetson AGX(aarch64 linux) before and saw no performance impact(more to say, denormal situation did not happen in tutorial codes).

FYI, aarch64 NEON's `flash to zero` mode is equivalent to SSE2 DAZ + FTZ.

https://qiita.com/syoyo/items/9d49823baeccbc5e2701 (in Japanese)

**Comment by Twinklebear** [comment]
Ah I see, I was wondering about this because some of the demos perform just similar to my old desktop (i7-4790k) (like the pathtracer), while stuff like cinebench or my old Rust ray tracer are about 1.6-1.8x faster on the M1. Some other demos perform better but it may vary by what the example is bottlenecked on then maybe.

One thing I did notice in the examples is that the interactive window framerate is much worse, I think this is an issue with the app (either the GL display or GLFW?) since they get much better FPS when run in offline benchmark mode.

**Comment by syoyo** [comment]
@Twinklebear I have merged the PR to `aarch64-v3.12.1`, but then found some issues.

When I add `--benchmark`, the app quits with `setting thread affinity failed`

FYI I got 50 fps(120 Mrays/s) on Threadripper 1950X and 4 fps(37 Mrays/s) on M1 for `pathtracer`.  
10x difference is big, but may be possible(2 ~ 3x cores * 2x freq/caches/faster memory * 2x vector(AVX))

**Comment by Twinklebear** [comment]
That's odd, the `--benchmark` issue I'm not able to reproduce after doing a clean checkout and build of the `aarch64-v3.12.1` branch. What do you get if you run it with `--verbose 4`? Here's what `./pathtracer --benchmark 10 100 --verbose 4` outputs for me:

```

Embree Ray Tracing Kernels 3.12.1 (6ef362f99af80c9dfe8dd2bfc582d9067897edc6)
  Compiler  : CLANG 12.0.0 (clang-1200.0.32.27)
  Build     : Release 
  Platform  : Mac OS X (32bit)
  CPU       : Unknown CPU ( MRA MRA MRA)
   Threads  : 8
   ISA      : XMM YMM SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 POPCNT AVX F16C RDRAND AVX2 FMA3 LZCNT BMI1 BMI2 NEON 2xNEON 
   Targets  : SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVXI AVX2 NEON 2xNEON 
   MXCSR    : FTZ=0, DAZ=0
  Config
    Threads : default
    ISA     : XMM YMM SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 POPCNT AVX F16C RDRAND AVX2 FMA3 LZCNT BMI1 BMI2 NEON 2xNEON 
    Targets : SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVXI AVX2 NEON 2xNEON  (supported)
              SSE2 SSE4.2 AVX AVX2  (compile time enabled)
    Features: intersection_filter 
    Tasking : TBB2021.1 TBB_header_interface_12010 TBB_lib_interface_12010 

================================================================================
  WARNING: "Flush to Zero" or "Denormals are Zero" mode not enabled 
           in the MXCSR control and status register. This can have a severe 
           performance impact. Please enable these modes for each application 
           thread the following way:

           #include "xmmintrin.h"
           #include "pmmintrin.h"

           _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
           _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
================================================================================


general:
  build threads      = 0
  build user threads = 0
  start_threads      = 1
  affinity           = 0
  frequency_level    = simd256
  hugepages          = disabled
  verbosity          = 4
  cache_size         = 134.218 MB
  max_spatial_split_replications = 1.2
triangles:
  accel              = default
  builder            = default
  traverser          = default
motion blur triangles:
  accel              = default
  builder            = default
  traverser          = default
quads:
  accel              = default
  builder            = default
  traverser          = default
motion blur quads:
  accel              = default
  builder            = default
  traverser          = default
line segments:
  accel              = default
  builder            = default
  traverser          = default
motion blur line segments:
  accel              = default
  builder            = default
  traverser          = default
hair:
  accel              = default
  builder            = default
  traverser          = default
motion blur hair:
  accel              = default
  builder            = default
  traverser          = default
subdivision surfaces:
  accel              = default
grids:
  accel              = default
  builder            = default
motion blur grids:
  accel              = default
  builder            = default
object_accel:
  min_leaf_size      = 1
  max_leaf_size      = 1
object_accel_mb:
  min_leaf_size      = 1
  max_leaf_size      = 1
[    0.004s,     0.00 MB virtual,     0.00 MB resident ] application start
[    0.005s,     0.00 MB virtual,     0.00 MB resident ] loading scene done
[    0.005s,     0.00 MB virtual,     0.00 MB resident ] converting scene done

scene statistics (pre-flattening):
  # transform nodes : 0
    # objects       : 0
  # triangle meshes : 8 ( 0.00 MB )
    # triangles     : 34
  # quad meshes     : 0 ( 0.00 MB )
    # quads         : 0
  # subdiv meshes   : 0 ( 0.00 MB )
    # patches       : 0
  # curve sets      : 0 ( 0.00 MB )
    # curves        : 0
  # grid meshes     : 0 ( 0.00 MB )
    # grids         : 0
  # point sets      : 0 ( 0.00 MB )
    # points        : 0
  # lights          : 1
  # cameras         : 0
  # materials       : 3

[    0.005s,     0.00 MB virtual,     0.00 MB resident ] flattening scene done

scene statistics (post-flattening):
  # transform nodes : 0
    # objects       : 0
  # triangle meshes : 8 ( 0.00 MB )
    # triangles     : 34
  # quad meshes     : 0 ( 0.00 MB )
    # quads         : 0
  # subdiv meshes   : 0 ( 0.00 MB )
    # patches       : 0
  # curve sets      : 0 ( 0.00 MB )
    # curves        : 0
  # grid meshes     : 0 ( 0.00 MB )
    # grids         : 0
  # point sets      : 0 ( 0.00 MB )
    # points        : 0
  # lights          : 1
  # cameras         : 0
  # materials       : 3

[    0.005s,     0.00 MB virtual,     0.00 MB resident ] populating tutorial scene done
[    0.005s,     0.00 MB virtual,     0.00 MB resident ] creating ISPC compatible scene done
[    0.005s,     0.00 MB virtual,     0.00 MB resident ] creating Embree objects done
               segments:          0
-----------------------------------
      flat_linear_curve:          0
     round_linear_curve:          0
  oriented_linear_curve:          0
      flat_bezier_curve:          0
     round_bezier_curve:          0
  oriented_bezier_curve:          0
     flat_bspline_curve:          0
    round_bspline_curve:          0
 oriented_bspline_curve:          0
     flat_hermite_curve:          0
    round_hermite_curve:          0
 oriented_hermite_curve:          0
 flat_catmull_rom_curve:          0
round_catmull_rom_curve:          0
oriented_catmull_rom_curve:          0
              triangles:         34
                  quads:          0
                   grid:          0
                subdivs:          0
                 sphere:          0
                   disc:          0
          oriented_disc:          0
               usergeom:          0
         instance_cheap:          0
     instance_expensive:          0
building BVH8<triangle4> using avx::BVH8BuilderSAH ...
finished BVH8<triangle4> : 0.08ms, 0.44 Mprim/s, 0.03 GB/s
  primitives = 34, vertices = 0, depth = 1
  total            : sah =   4.042 (100.00%), #bytes =    0.00 MB (100.00%), #nodes =       9 ( 87.50% filled), #bytes/prim =  59.29
  getAABBNodes     : sah =   1.000 ( 24.74%), #bytes =    0.00 MB ( 12.70%), #nodes =       1 (100.00% filled), #bytes/prim =   7.53
  leaves           : sah =   3.042 ( 75.26%), #bytes =    0.00 MB ( 87.30%), #nodes =       8 ( 85.00% filled), #bytes/prim =  51.76
    histogram      :  87.50%   0.00%  12.50%   0.00%   0.00%   0.00%   0.00%   0.00% 
  alloc : used =   0.002 MB,                                                             #bytes/prim =  59.29
  alloc : used =   0.002 MB, free =   0.001 MB, wasted =   0.000 MB, total =   0.003 MB, #bytes/prim =  88.94
  total : used =   0.003 MB, free =   0.000 MB, wasted =   0.000 MB, total =   0.003 MB, #bytes/prim = 101.65
  4K    : used =   0.000 MB, free =   0.000 MB, wasted =   0.000 MB, total =   0.000 MB, #bytes/prim =   0.00
  2M    : used =   0.000 MB, free =   0.000 MB, wasted =   0.000 MB, total =   0.000 MB, #bytes/prim =   0.00
  malloc: used =   0.003 MB, free =   0.000 MB, wasted =   0.000 MB, total =   0.003 MB, #bytes/prim = 101.65
  shared: used =   0.000 MB, free =   0.000 MB, wasted =   0.000 MB, total =   0.000 MB, #bytes/prim =   0.00
  estimatedSize = 2376, slotMask = 0, use_single_mode = 0, maxGrowSize = 1024, defaultBlockSize = 1024
  used blocks = A[1024, 0, 128] A[1024, 0, 128] A[1024, 0, 128] [END]
  free blocks = [END]
BENCHMARK_BUILD 0.00 441505.68 4.04 2016 BVH8<triangle4>
created scene intersector
  accels[0]
    intersector1  = avx2::BVH8Triangle4Intersector1Moeller
    intersector4  = avx2::BVH8Triangle4Intersector4HybridMoeller
    intersector8  = avx2::BVH8Triangle4Intersector8HybridMoeller
    intersectorN = avx2::BVH8Triangle4IntersectorStreamMoeller
selected scene intersector
  intersector1  = avx2::BVH8Triangle4Intersector1Moeller
  intersector4  = avx2::BVH8Triangle4Intersector4HybridMoeller
  intersector8  = avx2::BVH8Triangle4Intersector8HybridMoeller
  intersectorN = avx2::BVH8Triangle4IntersectorStreamMoeller
frame [  0 / 110]:    13.09 fps (skipped)
frame [  1 / 110]:    17.18 fps (skipped)
frame [  2 / 110]:    17.23 fps (skipped)
frame [  3 / 110]:    17.16 fps (skipped)
frame [  4 / 110]:    17.13 fps (skipped)
frame [  5 / 110]:    17.21 fps (skipped)
frame [  6 / 110]:    17.16 fps (skipped)
frame [  7 / 110]:    17.15 fps (skipped)
frame [  8 / 110]:    17.19 fps (skipped)
frame [  9 / 110]:    17.18 fps (skipped)
frame [ 10 - 110]:               min =    16.92 fps, avg =    17.15 fps, max =    17.26 fps, sigma =   0.01 (0.05%)
BENCHMARK_RENDER_MIN 16.92
BENCHMARK_RENDER_AVG 17.15
BENCHMARK_RENDER_MAX 17.26
BENCHMARK_RENDER_SIGMA 0.07
BENCHMARK_RENDER_AVG_SIGMA 0.01
BENCHMARK_RENDER_MRAYPS_MIN 37.33
BENCHMARK_RENDER_MRAYPS_AVG 37.84
BENCHMARK_RENDER_MRAYPS_MAX 38.07
BENCHMARK_RENDER_MRAYPS_SIGMA 0.16
BENCHMARK_RENDER_MRAYPS_AVG_SIGMA 0.02
```

Yeah I also see the UI FPS vs. non-UI FPS issue, I'm not quite sure on the cause of that. What's interesting is that with other UI apps based on SDL2 (https://github.com/Twinklebear/ChameleonRT) I don't see such a big difference in the actual render performance vs. the display rate. So it might be a GLFW specific issue to be fixed on M1

**Comment by syoyo** [comment]
@Twinklebear Ah, for `--benchmark`, We need to pass skip_frames and render_frames such like  `--benchmark 0 100`. Without args it quits with rendering 0 frames.

**Comment by syoyo** [comment]
I have now merged PR into master(and re-tagged `v3.12.1-aarch64`)

For FPS issue, I have filed it as an github issue : https://github.com/lighttransport/embree-aarch64/issues/50

**Pull request merged**
