### PR TITLE
Fix issue 42

### PR DESCRIPTION
**Pull request by maikschulze**
This fixes https://github.com/lighttransport/embree-aarch64/issues/42 

after fixing the crash by enabling SSE42 and AVX symbols, some update failures were revealed. Those have also been fixed.

I ran verify with and without ray packets and obtain complete passing:
[verify_avx2_emu_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5378985/verify_avx2_emu_with_packets.txt)
[verify_avx2_emu_without_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5378987/verify_avx2_emu_without_packets.txt)

Please test this thoroughly.

### CODE REVIEW

**Comment by syoyo** [comment]
After merging `travis` branch, Travis reports build failures in configuration: ` -DEMBREE_MAX_ISA=AVX2  -DEMBREE_NEON_AVX2_EMULATION=ON` 

https://travis-ci.org/github/lighttransport/embree-aarch64/jobs/735783948

**Comment by maikschulze** [comment]
Could you please quickly verify that the travis script is correct? File https://github.com/lighttransport/embree-aarch64/blob/travis/scripts/bootstrap-arm64-travis.sh  seems to have a typo in line 34 from my understanding.

**Comment by syoyo** [comment]
> Could you please quickly verify that the travis script is correct? File https://github.com/lighttransport/embree-aarch64/blob/travis/scripts/bootstrap-arm64-travis.sh seems to have a typo in line 34 from my understanding.

Good catch. I have fixed a typo and apparently it now compiles fine(got built timeout for AVX2 target on Travis): https://travis-ci.org/github/lighttransport/embree-aarch64/builds/735977093

**Comment by maikschulze** [comment]
Thank you for the update fix!

I have run into this as well and found it quite helpful to always print and log the modified CMake variables, for example through
`cmake -L -N -B ./_build/ `

The increased build time and binary size is quite unfortunate. I've briefly toyed with the SELECT_SYMBOL macros, binding them to AVX2 where it only used AVX, but I just into different issues. Currently, x64 AVX2 binaries use various embree::avx:: functions. My knowledge about this is rather limited. There may be better ways to ensure just NEON 2xNEON without larger changes.

**Comment by syoyo** [comment]
I have confirmed `verify` passes on local Jetson AGX(aarch64 linux) so merged!

Merge is done both into `aarch64-v3.12.0` and `main`(master. currently its `aarch64-v3.12.0`)

**Comment by syoyo** [comment]
I didn't know such cmake argument exists. Will add it to Travis and Github Actions build script at some point > cmake -L -N

**Pull request merged**
