### PR TITLE
Improving performance for Apple silicon based products

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
- Improving Minps/maxps in SSE2Neon
 - General SIMD optimizations
 - Enable FMA/NEON for intersections

### CODE REVIEW

**Comment by Developer-Ecosystem-Engineering** [comment]
We see the failures, reviewing.

**Comment by syoyo** [comment]
Good!

At least I could compile and run PR on Jetson AGX(aarch64 linux). Apparently there is no visual issues.

Let us give some time to review changes in detail.

**Comment by syoyo** [comment]
@maikschulze Could you please test this PR and check if things works well or not? As far as I've tested on my aarch64 linux(Jetson  AGX), it looks it works well(no hole/artifact issues)

**Comment by maikschulze** [comment]
Hi @syoyo ,

I've already been testing. My tests show good quality on: iOS arm64, Android arm64, Windows x64. No holes or other artifacts are visible. Performance looks very good on iOs.

Very nice changes!

**Comment by syoyo** [comment]
@maikschulze Awesome! Good to hear of it. Will soon merge the PR!

**Comment by syoyo** [comment]
Merged! Thank you for the contribution!

**Comment by Developer-Ecosystem-Engineering** [comment]
Thank you for accepting!

**Pull request merged**
